project:
  type: website
  output-dir: docs

website:
  title: "tzonniStam_all"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd

format:
  html:
    include-in-header:
      - text: |
          <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/css/lightbox.min.css" rel="stylesheet">
          <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/js/lightbox.min.js"></script>
