project:
  type: website
  output-dir: docs  # added manually


website:
  title: "tzonniStam_all"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd     # Add href here explicitly
        text: About         # Add text here explicitly


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


editor: visual

