project:
  type: website
  output-dir: docs  # added manually


website:
  title: "tzonniStam_all"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

